<?php $lang = $this->plugin('translate')->getTranslator()->getLocale(); ?>
<ul class="list-group">
<?php if ($activities instanceof \Zend\Paginator\Paginator):?>
    <li class="list-group-item agenda-item row">
        <?=$this->paginationControl($activities,
                'Elastic',
                'paginator/default', ['path' => $this->url($route)]); ?>
    </li>
<?php endif; ?>
    <table class="table table-striped">
        <thead>
            <td>#</td>
            <td>Dutch name</td>
            <td>English name</td>
            <td>Startdatum</td>
            <td>Subscriptions</td>
            <td>Organ</td>
            <td>Aangemaakt door</td>
            <td>Goedkeuringsstatus</td>
            <td></td>
        </thead>
        <tbody>
        <?php foreach($activities as $activity):?>
        <tr>
            <td><?= $activity['id'] ?></td>
            <td><?= $activity['dutch_name'] ?></td>
            <td><?= $activity['english_name'] ?></td>
            <td><?= $activity['begin_time']->format('Y-m-d H:i:s') ?></td>
            <td><?= $activity['subscriptions'] ?></td>
            <td><?= $activity['organ'] ?></td>
            <td><?= $activity['creator']?></td>
            <td></td>
            <td><td>
            <td><a href="<?php echo $this->url('admin_activity/view', ['id' => $activity['id']]);?>">Edit</a></td>
        </tr>
        <?php endforeach;?>
        </tbody>
    </table>
    <?php if (isset($moreLink)): ?>
    <li class="list-group-item agenda-item row">
        <h4><a href="<?= $moreLink;?>"><?=$this->translate('More');?></a></h4>
    </li>
    <?php endif;?>

    <?php if ($activities instanceof \Zend\Paginator\Paginator):?>
    <li class="list-group-item agenda-item row">
        <?=$this->paginationControl($activities,
                'Elastic',
                'paginator/default', ['path' => $this->url($route)]); ?>
    </li>
    <?php endif; ?>
</ul>
